# Working with a real world data-set using SQL and Python

## Chicago Public Schools - Progress Report Cards (2011-2012)

The city of Chicago released a dataset showing all school level performance data used to create School Report Cards for the 2011-2012 school year. The dataset is available from the Chicago Data Portal: [https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

This dataset includes a large number of metrics. Start by familiarizing yourself with the types of metrics in the database: [https://data.cityofchicago.org/api/assets/AAD41A13-BE8A-4E67-B1F5-86E711E09D5F?download=true](https://data.cityofchicago.org/api/assets/AAD41A13-BE8A-4E67-B1F5-86E711E09D5F?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&download=true&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

**NOTE**:

Do not download the dataset directly from City of Chicago portal. Instead download a static copy which is a more database friendly version from this <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">link</a>.

Now review some of its contents.

### Connect to the database

In [ ]:
import csv, sqlite3

con = sqlite3.connect("data/RealWorldData.db")
cur = con.cursor()

In [ ]:
!pip install -q pandas==1.1.5

     |████████████████████████████████| 9.5 MB 5.1 MB/s

In [ ]:
%load_ext sql

In [ ]:
%sql sqlite:///data/RealWorldData.db

'Connected: @data/RealWorldData.db'

### Store the dataset in a Table

##### In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. To analyze the data

##### using SQL, it first needs to be stored in the database.

##### We will first read the csv files  from the given url  into pandas dataframes

##### Next we will be using the  df.to_sql() function to convert each csv file  to a table in sqlite  with the csv data loaded in it.

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
df = pd.read_csv("data/ChicagoCensusData.csv")#"https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv"
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")

df = pd.read_csv('data/ChicagoCrimeData.csv')#"https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv"
df.to_sql("CHICAGO_CRIME_DATA", con, if_exists='replace', index=False, method="multi")

df = pd.read_csv("data/ChicagoPublicSchools.csv")#"https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv"
df.to_sql("CHICAGO_PUBLIC_SCHOOLS_DATA", con, if_exists='replace', index=False, method="multi")

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:2882: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,

### Query the database system catalog to retrieve table metadata

In [ ]:
# type in your query to retrieve list of all tables in the database
%sql select name from sqlite_master where type='table'

 * sqlite:///data/RealWorldData.db
Done.

[('CENSUS_DATA',), ('CHICAGO_CRIME_DATA',), ('CHICAGO_PUBLIC_SCHOOLS_DATA',)]

Double-click **here** for a hint

<!--
In sqlite the system catalog table called sqlite_master contains the table metadata
-->

### Query the database system catalog to retrieve column metadata

##### The SCHOOLS table contains a large number of columns. How many columns does this table have?

In [ ]:
# type in your query to retrieve the number of columns in the SCHOOLS table

 * sqlite:///data/RealWorldData.db
Done.

[(78,)]

Now retrieve the the list of columns in SCHOOLS table and their column type (datatype) and length.

In [ ]:
# type in your query to retrieve all column names in the SCHOOLS table along with their datatypes and length
%sql select name,type,length(type) from pragma_table_info('chicago_public_schools_data')

 * sqlite:///data/RealWorldData.db
Done.

[('School_ID', 'INTEGER', 7),
 ('NAME_OF_SCHOOL', 'TEXT', 4),
 ('Elementary, Middle, or High School', 'TEXT', 4),
 ('Street_Address', 'TEXT', 4),
 ('City', 'TEXT', 4),
 ('State', 'TEXT', 4),
 ('ZIP_Code', 'INTEGER', 7),
 ('Phone_Number', 'TEXT', 4),
 ('Link', 'TEXT', 4),
 ('Network_Manager', 'TEXT', 4),
 ('Collaborative_Name', 'TEXT', 4),
 ('Adequate_Yearly_Progress_Made_', 'TEXT', 4),
 ('Track_Schedule', 'TEXT', 4),
 ('CPS_Performance_Policy_Status', 'TEXT', 4),
 ('CPS_Performance_Policy_Level', 'TEXT', 4),
 ('HEALTHY_SCHOOL_CERTIFIED', 'TEXT', 4),
 ('Safety_Icon', 'TEXT', 4),
 ('SAFETY_SCORE', 'REAL', 4),
 ('Family_Involvement_Icon', 'TEXT', 4),
 ('Family_Involvement_Score', 'TEXT', 4),
 ('Environment_Icon', 'TEXT', 4),
 ('Environment_Score', 'REAL', 4),
 ('Instruction_Icon', 'TEXT', 4),
 ('Instruction_Score', 'REAL', 4),
 ('Leaders_Icon', 'TEXT', 4),
 ('Leaders_Score', 'TEXT', 4),
 ('Teachers_Icon', 'TEXT', 4),
 ('Teachers_Score', 'TEXT', 4),
 ('Parent_Engagement_Icon', 'TEXT', 4),
 ('Parent_Engagement_Score', 'TEXT', 4),
 ('Parent_Environment_Icon', 'TEXT', 4),
 ('Parent_Environment_Score', 'TEXT', 4),
 ('AVERAGE_STUDENT_ATTENDANCE', 'TEXT', 4),
 ('Rate_of_Misconducts__per_100_students_', 'REAL', 4),
 ('Average_Teacher_Attendance', 'TEXT', 4),
 ('Individualized_Education_Program_Compliance_Rate', 'TEXT', 4),
 ('Pk_2_Literacy__', 'TEXT', 4),
 ('Pk_2_Math__', 'TEXT', 4),
 ('Gr3_5_Grade_Level_Math__', 'TEXT', 4),
 ('Gr3_5_Grade_Level_Read__', 'TEXT', 4),
 ('Gr3_5_Keep_Pace_Read__', 'TEXT', 4),
 ('Gr3_5_Keep_Pace_Math__', 'TEXT', 4),
 ('Gr6_8_Grade_Level_Math__', 'TEXT', 4),
 ('Gr6_8_Grade_Level_Read__', 'TEXT', 4),
 ('Gr6_8_Keep_Pace_Math_', 'TEXT', 4),
 ('Gr6_8_Keep_Pace_Read__', 'TEXT', 4),
 ('Gr_8_Explore_Math__', 'TEXT', 4),
 ('Gr_8_Explore_Read__', 'TEXT', 4),
 ('ISAT_Exceeding_Math__', 'REAL', 4),
 ('ISAT_Exceeding_Reading__', 'REAL', 4),
 ('ISAT_Value_Add_Math', 'REAL', 4),
 ('ISAT_Value_Add_Read', 'REAL', 4),
 ('ISAT_Value_Add_Color_Math', 'TEXT', 4),
 ('ISAT_Value_Add_Color_Read', 'TEXT', 4),
 ('Students_Taking__Algebra__', 'TEXT', 4),
 ('Students_Passing__Algebra__', 'TEXT', 4),
 ('9th Grade EXPLORE (2009)', 'TEXT', 4),
 ('9th Grade EXPLORE (2010)', 'TEXT', 4),
 ('10th Grade PLAN (2009)', 'TEXT', 4),
 ('10th Grade PLAN (2010)', 'TEXT', 4),
 ('Net_Change_EXPLORE_and_PLAN', 'TEXT', 4),
 ('11th Grade Average ACT (2011)', 'TEXT', 4),
 ('Net_Change_PLAN_and_ACT', 'TEXT', 4),
 ('College_Eligibility__', 'TEXT', 4),
 ('Graduation_Rate__', 'TEXT', 4),
 ('College_Enrollment_Rate__', 'TEXT', 4),
 ('COLLEGE_ENROLLMENT', 'INTEGER', 7),
 ('General_Services_Route', 'INTEGER', 7),
 ('Freshman_on_Track_Rate__', 'TEXT', 4),
 ('X_COORDINATE', 'REAL', 4),
 ('Y_COORDINATE', 'REAL', 4),
 ('Latitude', 'REAL', 4),
 ('Longitude', 'REAL', 4),
 ('COMMUNITY_AREA_NUMBER', 'INTEGER', 7),
 ('COMMUNITY_AREA_NAME', 'TEXT', 4),
 ('Ward', 'INTEGER', 7),
 ('Police_District', 'INTEGER', 7),
 ('Location', 'TEXT', 4)]

## Problems

### Problem 1
How many Elementary Schools are in the dataset?

In [ ]:
%sql select count(*) from chicago_public_schools_data where "Elementary, Middle, or High School"='ES'

 * sqlite:///data/RealWorldData.db
Done.

[(462,)]

### Problem 2

##### What is the highest Safety Score?

In [ ]:
%%sql 
select max(SafeTy_score) as MAX_SAFTEY_SCORE 
  from chicago_public_schools_data

 * sqlite:///data/RealWorldData.db
Done.

[(99.0,)]

### Problem 3

##### Which schools have highest Safety Score?

In [ ]:
%%sql
select name_of_school, safety_score
  from chicago_public_schools_data
  where safety_score = (select max(safety_score) from chicago_public_schools_data)

 * sqlite:///data/RealWorldData.db
Done.

[('Abraham Lincoln Elementary School', 99.0),
 ('Alexander Graham Bell Elementary School', 99.0),
 ('Annie Keller Elementary Gifted Magnet School', 99.0),
 ('Augustus H Burley Elementary School', 99.0),
 ('Edgar Allan Poe Elementary Classical School', 99.0),
 ('Edgebrook Elementary School', 99.0),
 ('Ellen Mitchell Elementary School', 99.0),
 ('James E McDade Elementary Classical School', 99.0),
 ('James G Blaine Elementary School', 99.0),
 ('LaSalle Elementary Language Academy', 99.0),
 ('Mary E Courtenay Elementary Language Arts Center', 99.0),
 ('Northside College Preparatory High School', 99.0),
 ('Northside Learning Center High School', 99.0),
 ('Norwood Park Elementary School', 99.0),
 ('Oriole Park Elementary School', 99.0),
 ('Sauganash Elementary School', 99.0),
 ('Stephen Decatur Classical Elementary School', 99.0),
 ('Talman Elementary School', 99.0),
 ('Wildwood Elementary School', 99.0)]

### Problem 4

##### What are the top 10 schools with the highest "Average Student Attendance"?

In [ ]:
%%sql 
select name_of_school, average_student_attendance 
  from chicago_public_schools_data
  order by average_student_attendance desc 
  limit 10

 * sqlite:///data/RealWorldData.db
Done.

[('John Charles Haines Elementary School', '98.40%'),
 ('James Ward Elementary School', '97.80%'),
 ('Edgar Allan Poe Elementary Classical School', '97.60%'),
 ('Orozco Fine Arts & Sciences Elementary School', '97.60%'),
 ('Rachel Carson Elementary School', '97.60%'),
 ('Annie Keller Elementary Gifted Magnet School', '97.50%'),
 ('Andrew Jackson Elementary Language Academy', '97.40%'),
 ('Lenart Elementary Regional Gifted Center', '97.40%'),
 ('Disney II Magnet School', '97.30%'),
 ('John H Vanderpoel Elementary Magnet School', '97.20%')]

### Problem 5

##### Retrieve the list of 5 Schools with the lowest Average Student Attendance sorted in ascending order based on attendance

In [ ]:
%%sql 
select name_of_school, average_student_attendance 
  from chicago_public_schools_data
  order by average_student_attendance 
  limit 5

 * sqlite:///data/RealWorldData.db
Done.

[('Velma F Thomas Early Childhood Center', None),
 ('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%')]

### Problem 6

##### Now remove the '%' sign from the above result set for Average Student Attendance column

In [ ]:
%%sql 
select name_of_school, replace(average_student_attendance,'%','') 
  from chicago_public_schools_data
  order by average_student_attendance 
  limit 5

 * sqlite:///data/RealWorldData.db
Done.

[('Velma F Thomas Early Childhood Center', None),
 ('Richard T Crane Technical Preparatory High School', '57.90'),
 ('Barbara Vick Early Childhood & Family Center', '60.90'),
 ('Dyett High School', '62.50'),
 ('Wendell Phillips Academy High School', '63.00')]

### Problem 7

##### Which Schools have Average Student Attendance lower than 70%?

In [ ]:
%%sql 
select name_of_school, average_student_attendance
  from chicago_public_schools_data
  where 
    cast(replace(average_student_attendance,'%','') as double)<70
  order by average_student_attendance

 * sqlite:///data/RealWorldData.db
Done.

[('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%'),
 ('Orr Academy High School', '66.30%'),
 ('Manley Career Academy High School', '66.80%'),
 ('Chicago Vocational Career Academy High School', '68.80%'),
 ('Roberto Clemente Community Academy High School', '69.60%')]

### Problem 8

##### Get the total College Enrollment for each Community Area

In [ ]:
%%sql 
select community_area_name, sum(college_enrollment) AS total_college_enrollments
  from chicago_public_schools_data
  group by community_area_name

 * sqlite:///data/RealWorldData.db
Done.

[('ALBANY PARK', 6864),
 ('ARCHER HEIGHTS', 4823),
 ('ARMOUR SQUARE', 1458),
 ('ASHBURN', 6483),
 ('AUBURN GRESHAM', 4175),
 ('AUSTIN', 10933),
 ('AVALON PARK', 1522),
 ('AVONDALE', 3640),
 ('BELMONT CRAGIN', 14386),
 ('BEVERLY', 1636),
 ('BRIDGEPORT', 3167),
 ('BRIGHTON PARK', 9647),
 ('BURNSIDE', 549),
 ('CALUMET HEIGHTS', 1568),
 ('CHATHAM', 5042),
 ('CHICAGO LAWN', 7086),
 ('CLEARING', 2085),
 ('DOUGLAS', 4670),
 ('DUNNING', 4568),
 ('EAST GARFIELD PARK', 5337),
 ('EAST SIDE', 5305),
 ('EDGEWATER', 4600),
 ('EDISON PARK', 910),
 ('ENGLEWOOD', 6832),
 ('FOREST GLEN', 1431),
 ('FULLER PARK', 531),
 ('GAGE PARK', 9915),
 ('GARFIELD RIDGE', 4552),
 ('GRAND BOULEVARD', 2809),
 ('GREATER GRAND CROSSING', 4051),
 ('HEGEWISCH', 963),
 ('HERMOSA', 3975),
 ('HUMBOLDT PARK', 8620),
 ('HYDE PARK', 1930),
 ('IRVING PARK', 7764),
 ('JEFFERSON PARK', 1755),
 ('KENWOOD', 4287),
 ('LAKE VIEW', 7055),
 ('LINCOLN PARK', 5615),
 ('LINCOLN SQUARE', 4132),
 ('LOGAN SQUARE', 7351),
 ('LOOP', 871),
 ('LOWER WEST SIDE', 7257),
 ('MCKINLEY PARK', 1552),
 ('MONTCLARE', 1317),
 ('MORGAN PARK', 3271),
 ('MOUNT GREENWOOD', 2091),
 ('NEAR NORTH SIDE', 3362),
 ('NEAR SOUTH SIDE', 1378),
 ('NEAR WEST SIDE', 7975),
 ('NEW CITY', 7922),
 ('NORTH CENTER', 7541),
 ('NORTH LAWNDALE', 5146),
 ('NORTH PARK', 4210),
 ('NORWOOD PARK', 6469),
 ('OAKLAND', 140),
 ('OHARE', 786),
 ('PORTAGE PARK', 6954),
 ('PULLMAN', 1620),
 ('RIVERDALE', 1547),
 ('ROGERS PARK', 4068),
 ('ROSELAND', 7020),
 ('SOUTH CHICAGO', 4043),
 ('SOUTH DEERING', 1859),
 ('SOUTH LAWNDALE', 14793),
 ('SOUTH SHORE', 4543),
 ('UPTOWN', 4388),
 ('WASHINGTON HEIGHTS', 4006),
 ('WASHINGTON PARK', 2648),
 ('WEST ELSDON', 3700),
 ('WEST ENGLEWOOD', 5946),
 ('WEST GARFIELD PARK', 2622),
 ('WEST LAWN', 4207),
 ('WEST PULLMAN', 3240),
 ('WEST RIDGE', 8197),
 ('WEST TOWN', 9429),
 ('WOODLAWN', 4206)]

Double-click **here** for a hint

<!--
Verify the exact name of the Enrollment column in the database
Use the SUM() function to add up the Enrollments for each Community Area
-->

### Problem 9

##### Get the 5 Community Areas with the least total College Enrollment  sorted in ascending order

In [ ]:
%%sql 
select community_area_name, sum(college_enrollment) AS total_college_enrollments
  from chicago_public_schools_data
  group by community_area_name
  order by total_college_enrollments
  limit 5

 * sqlite:///data/RealWorldData.db
Done.

[('OAKLAND', 140),
 ('FULLER PARK', 531),
 ('BURNSIDE', 549),
 ('OHARE', 786),
 ('LOOP', 871)]

### Problem 10

##### List 5 schools with lowest safety score.

In [ ]:
%%sql 
select name_of_school, safety_score
  from chicago_public_schools_data
  where safety_score != 'None'
  order by safety_score
  limit 5

 * sqlite:///data/RealWorldData.db
Done.

[('Edmond Burke Elementary School', 1.0),
 ("Luke O'Toole Elementary School", 5.0),
 ('George W Tilton Elementary School', 6.0),
 ('Foster Park Elementary School', 11.0),
 ('Emil G Hirsch Metropolitan High School', 13.0)]

### Problem 11

##### Get the hardship index for the community area which has College Enrollment of 4368

In [ ]:
%%sql
select hardship_index 
  from census_data CD, chicago_public_schools_data CPS 
  where CD.community_area_number = CPS.community_area_number and college_enrollment = 4368

 * sqlite:///data/RealWorldData.db
Done.

[(6.0,)]

### Problem 12

##### Get the hardship index for the community area which has the highest value for College Enrollment

In [ ]:
%%sql
select community_area_number, community_area_name, hardship_index 
  from census_data
  where
    community_area_number in ( select community_area_number from chicago_public_schools_data order by college_enrollment desc limit 1 )

 * sqlite:///data/RealWorldData.db
Done.

[(5.0, 'North Center', 6.0)]

# Mount GDrive and Directory

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/0zProject/COURSERA/sql-data-science

Mounted at /content/drive
/content/drive/MyDrive/0zProject/COURSERA/sql-data-science